export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";
export const SAVE_FORM_DATA = "SAVE_FORM_DATA";
export const FETCH_OUT_LIST = "FETCH_OUT_LIST";
export const UPDATE_LIST = "UPDATE_LIST";
export const ERROR_FORM_DATA = "ERROR_FORM_DATA";
